---
- name: Install dnf packages 
  become: true
  dnf:
    name:
      # essential build tools (gcc, make, etc)
      - "@development-tools"
      - libtool
      - python3

      # For bluetooth selinux fix
      - selinux-policy
      - python2-libselinux

      # Audio / CRAS dependencies
      - acpid
      - libudev-devel
      - sbc-devel
      - alsa-lib-devel
      - iniparser-devel
      - ladspa-devel
      - speex-devel
      - speexdsp-devel
    state: latest 

